import { ProjectInfo } from './detector.service';

export function generateDockerfile(projectInfo: ProjectInfo): string {
  if (projectInfo.language === 'Node.js') {
    return `# Generated by DeploySense
FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci --only=production

# Copy application code
COPY . .

# Expose port
EXPOSE ${projectInfo.port || 3000}

# Start application
CMD ["${projectInfo.startCommand || 'npm start'}"]
`;
  }

  if (projectInfo.language === 'Python') {
    return `# Generated by DeploySense
FROM python:3.11-slim

WORKDIR /app

# Copy requirements
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Expose port
EXPOSE ${projectInfo.port || 5000}

# Start application
CMD ["${projectInfo.startCommand || 'python app.py'}"]
`;
  }

  // Generic Dockerfile
  return `# Generated by DeploySense
FROM alpine:latest

WORKDIR /app

COPY . .

EXPOSE ${projectInfo.port || 3000}

CMD ["echo", "Please configure your start command"]
`;
}

export function generateCICDPipeline(projectInfo: ProjectInfo): string {
  if (projectInfo.language === 'Node.js') {
    return `# Generated by DeploySense
name: Deploy to Production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test || echo "No tests found"

    - name: Build application
      run: npm run build || echo "No build script"

    - name: Build Docker image
      run: docker build -t \${{ github.repository }}:latest .

    - name: Deploy
      run: echo "Deploy to your platform here"
      # Add your deployment commands here
`;
  }

  if (projectInfo.language === 'Python') {
    return `# Generated by DeploySense
name: Deploy to Production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: python -m pytest || echo "No tests found"

    - name: Build Docker image
      run: docker build -t \${{ github.repository }}:latest .

    - name: Deploy
      run: echo "Deploy to your platform here"
      # Add your deployment commands here
`;
  }

  return `# Generated by DeploySense
name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy
      run: echo "Configure your deployment"
`;
}